Fix grahql file loading when used as flake

diff --git a/nixpkgs-review-checks b/nixpkgs-review-checks
--- a/nixpkgs-review-checks
+++ b/nixpkgs-review-checks
@@ -52,7 +52,14 @@ else
 
         # skip posting reports if ofborg already build this exact package
         arch=$(nix-instantiate --eval --json --expr builtins.currentSystem | jq -r)
-        ofborg_state=$(curl -H "Authorization: token $GITHUB_TOKEN" -X POST https://api.github.com/graphql --data "{ \"query\": \"$(sed 's/"/\\"/g' "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/ofborg.graphql | tr -d '\n')\", \"variables\": \"{\\\"PR\\\": $PR}\"}" -s | jq -r ".[][][][][][][][][][][][][]|select(.name | contains(\"passthru.tests on $arch\")).conclusion")
+        if [[ ! -v NIXPKGS_REVIEW_CHECKS_GRAPHQL_FILE ]]; then
+          NIXPKGS_REVIEW_CHECKS_GRAPHQL_FILE="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/ofborg.graphql
+        fi
+        if [[ ! -e $NIXPKGS_REVIEW_CHECKS_GRAPHQL_FILE ]]; then
+          echo "Can't find graphql file at $NIXPKGS_REVIEW_CHECKS_GRAPHQL_FILE"
+          exit 1
+        fi
+        ofborg_state=$(curl -H "Authorization: token $GITHUB_TOKEN" -X POST https://api.github.com/graphql --data "{ \"query\": \"$(sed 's/"/\\"/g' "$NIXPKGS_REVIEW_CHECKS_GRAPHQL_FILE" | tr -d '\n')\", \"variables\": \"{\\\"PR\\\": $PR}\"}" -s | jq -r ".[][][][][][][][][][][][][]|select(.name | contains(\"passthru.tests on $arch\")).conclusion")
 
         # report contains one summary, one package was build and ofborg reported success for building this package
         if [[ $(rg -co '</summary>' report.md) == 1 && $(rg -co "1 package built:" report.md) == 1 && -z $(rg -co "following issues got" report.md) && $ofborg_state == SUCCESS ]]; then
